[language-server.clangd]
command = "clangd"
args = ["--compile-commands-dir=../build", "--query-driver=/usr/bin/c++,/usr/bin/g++,/usr/bin/gcc"]

[[language]]
name = "cpp"
language-servers = ["clangd"]
comment-token = "///"
indent = {tab-width = 4, unit = " "}
auto-format = true

